joint_limits:
  shoulder_pan_joint:
    has_acceleration_limits: false
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_effort: 150.0
    max_position: !degrees  360.0
    max_velocity: !degrees  180.0
    min_position: !degrees -360.0

  shoulder_lift_joint:
    has_acceleration_limits: false
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_effort: 150.0
    max_position: !degrees  360.0
    max_velocity: !degrees  180.0
    min_position: !degrees -360.0

  elbow_joint:
    has_acceleration_limits: false
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_effort: 150.0
    max_position: !degrees  180.0
    max_velocity: !degrees  180.0
    min_position: !degrees -180.0

  wrist_1_joint:
    has_acceleration_limits: false
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_effort: 28.0
    max_position: !degrees  360.0
    max_velocity: !degrees  180.0
    min_position: !degrees -360.0

  wrist_2_joint:
    has_acceleration_limits: false
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_effort: 28.0
    max_position: !degrees  360.0
    max_velocity: !degrees  180.0
    min_position: !degrees -360.0

  wrist_3_joint:
    has_acceleration_limits: false
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_effort: 28.0
    max_position: !degrees  360.0
    max_velocity: !degrees  180.0
    min_position: !degrees -360.0

  # Gripper Sуглоби
  robotiq_85_left_finger_tip_joint:
    has_acceleration_limits: false
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_effort: 10.0
    max_position: !degrees  90.0  # Встановіть відповідні значення
    max_velocity: !degrees  45.0   # Встановіть відповідне значення
    min_position: !degrees 0.0

  robotiq_85_left_inner_knuckle_joint:
    has_acceleration_limits: false
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_effort: 10.0
    max_position: !degrees  90.0
    max_velocity: !degrees  45.0
    min_position: !degrees 0.0

  robotiq_85_left_knuckle_joint:
    has_acceleration_limits: false
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_effort: 10.0
    max_position: !degrees  90.0
    max_velocity: !degrees  45.0
    min_position: !degrees 0.0

  robotiq_85_right_finger_tip_joint:
    has_acceleration_limits: false
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_effort: 10.0
    max_position: !degrees  90.0
    max_velocity: !degrees  45.0
    min_position: !degrees 0.0

  robotiq_85_right_inner_knuckle_joint:
    has_acceleration_limits: false
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_effort: 10.0
    max_position: !degrees  90.0
    max_velocity: !degrees  45.0
    min_position: !degrees 0.0

  robotiq_85_right_knuckle_joint:
    has_acceleration_limits: false
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_effort: 10.0
    max_position: !degrees  90.0
    max_velocity: !degrees  45.0
    min_position: !degrees 0.0
